# Generated by Django 3.2.4 on 2022-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20220818_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3, null=True),
        ),
    ]
